feat: change overloaded private method name (#48)
I am attempting to pull the sdk in another gradle package and the compile fails looking for ByteString 

```
/Users/gautamkanvinde/repos/client-sdk-examples/java-gradle/lib/src/main/java/momento/client/example/Library.java:11: error: cannot access ByteString
    CacheSetResponse resp = client.set("key", "value", 1000);
                                  ^
  class file for com.google.protobuf.ByteString not found
1 error
```

I have a theory that this is due to the overloaded methods and wanted to test this out quick.